### ISSUE TITLE
ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.

### ISSUE THREAD

**Issue by scrawfordeng** [BiRG/pyopls#3]
Good afternoon,

When running the example code for Validator I am unable to get the OPLSValidator to fit without throwing the ValueError: Only one class present in y_true. ROC AUC score is not defined in that case.

Not sure if this has something to do with my setup or if others are having this issue as well.

Thanks!
Scott

**Comment by dpfoose** [comment]
Running the sample code exactly as provided should work. Perhaps something is wrong with how the test dataset is being loaded?
The test data for the OPLSValidator example is provided by `sklearn.datasets.load_wine`. There might be an issue there, or in the filtering by the target variable:
`df = df[df.classification.isin((0, 1))`
Or the conversion from 0/1 to -1/+1:
`target = df.classification.apply(lambda x: 1 if x else -1)  # discriminant for class 1 vs class 0`

**Comment by dpfoose** [comment]
@scrawfordeng I am closing this issue due to a lack of response. Please let me know if you still have this issue after following my suggested solution so I can reopen the issue.
Thanks,
Daniel Foose
